apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api2
  namespace: monorepo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api2
  template:
    metadata:
      labels:
        app: backend-api2
    spec:
      containers:
      - name: backend-api2
        image: backend-api2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api2
  namespace: monorepo-app
spec:
  type: NodePort
  selector:
    app: backend-api2
  ports:
  - port: 5000
    targetPort: 5000
    
