apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api1
  namespace: monorepo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api1
  template:
    metadata:
      labels:
        app: backend-api1
    spec:
      containers:
      - name: backend-api1
        image: backend-api1:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api1
  namespace: monorepo-app
spec:
  type: NodePort
  selector:
    app: backend-api1
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30400
