apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api-2
  template:
    metadata:
      labels:
        app: backend-api-2
    spec:
      containers:
        - name: backend-api-2
          image: backend-api-2:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api-2
spec:
  selector:
    app: backend-api-2
  ports:
    - port: 3000
      targetPort: 3000
