apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app-1
  template:
    metadata:
      labels:
        app: frontend-app-1
    spec:
      containers:
        - name: frontend-app-1
          image: frontend-app-1:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app-1
spec:
  selector:
    app: frontend-app-1
  ports:
    - port: 80
      targetPort: 80
