apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app-3
  template:
    metadata:
      labels:
        app: frontend-app-3
    spec:
      containers:
        - name: frontend-app-3
          image: frontend-app-3:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-app-3
spec:
  selector:
    app: frontend-app-3
  ports:
    - port: 80
      targetPort: 80
